plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_34"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_57"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_4"))
}
        