plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_33"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_10"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_35"))
}
        