plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_54"))
    implementation(project(":layer_0:module_0_56"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_43"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_40"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_55"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_61"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_32"))
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_35"))
    implementation(project(":layer_0:module_0_66"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_68"))
}
        