plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_12"))
    implementation(project(":layer_0:module_0_6"))
    implementation(project(":layer_0:module_0_50"))
    implementation(project(":layer_0:module_0_11"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_5"))
    implementation(project(":layer_0:module_0_28"))
    implementation(project(":layer_0:module_0_31"))
    implementation(project(":layer_0:module_0_65"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_36"))
    implementation(project(":layer_0:module_0_53"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_37"))
    implementation(project(":layer_0:module_0_41"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_21"))
    implementation(project(":layer_0:module_0_27"))
    implementation(project(":layer_0:module_0_26"))
    implementation(project(":layer_0:module_0_24"))
    implementation(project(":layer_0:module_0_1"))
    implementation(project(":layer_0:module_0_67"))
    implementation(project(":layer_0:module_0_4"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_58"))
    implementation(project(":layer_0:module_0_45"))
    implementation(project(":layer_0:module_0_18"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_19"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_59"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_35"))
}
        