plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_0:module_0_14"))
    implementation(project(":layer_0:module_0_63"))
    implementation(project(":layer_0:module_0_9"))
    implementation(project(":layer_0:module_0_48"))
    implementation(project(":layer_0:module_0_7"))
    implementation(project(":layer_0:module_0_46"))
    implementation(project(":layer_0:module_0_42"))
    implementation(project(":layer_0:module_0_17"))
    implementation(project(":layer_0:module_0_70"))
    implementation(project(":layer_0:module_0_15"))
    implementation(project(":layer_0:module_0_2"))
    implementation(project(":layer_0:module_0_25"))
    implementation(project(":layer_0:module_0_39"))
    implementation(project(":layer_0:module_0_30"))
    implementation(project(":layer_0:module_0_22"))
    implementation(project(":layer_0:module_0_60"))
    implementation(project(":layer_0:module_0_16"))
    implementation(project(":layer_0:module_0_49"))
    implementation(project(":layer_0:module_0_62"))
    implementation(project(":layer_0:module_0_23"))
    implementation(project(":layer_0:module_0_3"))
    implementation(project(":layer_0:module_0_29"))
    implementation(project(":layer_0:module_0_47"))
    implementation(project(":layer_0:module_0_20"))
    implementation(project(":layer_0:module_0_44"))
    implementation(project(":layer_0:module_0_52"))
    implementation(project(":layer_0:module_0_38"))
    implementation(project(":layer_0:module_0_8"))
    implementation(project(":layer_0:module_0_64"))
    implementation(project(":layer_0:module_0_13"))
    implementation(project(":layer_0:module_0_69"))
    implementation(project(":layer_0:module_0_56"))
}
        