plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_3:module_3_141"))
    implementation(project(":layer_3:module_3_128"))
    implementation(project(":layer_3:module_3_118"))
    implementation(project(":layer_3:module_3_129"))
    implementation(project(":layer_3:module_3_117"))
    implementation(project(":layer_3:module_3_130"))
    implementation(project(":layer_3:module_3_112"))
    implementation(project(":layer_3:module_3_106"))
    implementation(project(":layer_3:module_3_144"))
    implementation(project(":layer_3:module_3_121"))
    implementation(project(":layer_3:module_3_143"))
    implementation(project(":layer_3:module_3_136"))
    implementation(project(":layer_3:module_3_113"))
    implementation(project(":layer_3:module_3_133"))
    implementation(project(":layer_3:module_3_116"))
    implementation(project(":layer_3:module_3_126"))
    implementation(project(":layer_3:module_3_123"))
    implementation(project(":layer_3:module_3_125"))
    implementation(project(":layer_3:module_3_127"))
    implementation(project(":layer_3:module_3_122"))
    implementation(project(":layer_3:module_3_142"))
    implementation(project(":layer_3:module_3_139"))
    implementation(project(":layer_3:module_3_120"))
    implementation(project(":layer_3:module_3_124"))
    implementation(project(":layer_3:module_3_140"))
    implementation(project(":layer_3:module_3_111"))
    implementation(project(":layer_3:module_3_138"))
    implementation(project(":layer_3:module_3_114"))
    implementation(project(":layer_3:module_3_119"))
    implementation(project(":layer_3:module_3_109"))
    implementation(project(":layer_3:module_3_137"))
    implementation(project(":layer_3:module_3_110"))
    implementation(project(":layer_3:module_3_108"))
    implementation(project(":layer_3:module_3_115"))
    implementation(project(":layer_3:module_3_105"))
    implementation(project(":layer_3:module_3_135"))
    implementation(project(":layer_3:module_3_132"))
    implementation(project(":layer_3:module_3_107"))
    implementation(project(":layer_3:module_3_131"))
}
        