name: Build

on:
  push:
    branches: [ main]
  pull_request:
  schedule:
      - cron: '0 */3 * * *' 

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        java: [17]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ matrix.java }}

      - name: Execute assemble
        run: |
          bash replacer
          git config user.email inaki.seri@gmail.com
          git config user.name "inaki"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cdsap/MiddleBottleneck200Modules

          git add .
          git commit -m "change $RANDOM"
          git push origin main
          ./gradlew testDebug
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_TOKEN }}

